dependency fix
was causing this again:

Error: [$injector:unpr] Unknown provider: $$cookieReaderProvider <- $$cookieReader <- $cookies <- $cookieStore <- $translateCookieStorage <- $translateLocalStorage <- $translate <- $cookies